#!/bin/env python3

# 1 create a greeting for your program .
# 2 Ask the user for the city that they grew up in .
# 3 Ask the user for the name of a pet .
# 4 Combine the name of their city and pet and show them their band name .
# 5 Make sure the name of their city and pet and show them their band name .
# 





city = input("Enter the name of city that you grew in : ")

pet = input("Enter the name of pet : ")

print("your band name could be : " + city + " " + pet )