#!/usr/bin/env python3
art = (
'''
┌─┐┬┌┐ ┌─┐┌┐┌┌─┐┌─┐┌─┐┬  
├┤ │├┴┐│ ││││├─┤│  │  │  
└  ┴└─┘└─┘┘└┘┴ ┴└─┘└─┘┴  
┌─┐┌─┐┌─┐ ┬ ┬┌─┐┌┐┌┌─┐┌─┐
└─┐├┤ │─┼┐│ │├┤ ││││  ├┤ 
└─┘└─┘└─┘└└─┘└─┘┘└┘└─┘└─┘
'''
)

print(art)

num = int(input("enter the desired number for fibonacci"))

for i in range(num):

